FROM python:3.11-alpine

WORKDIR /app

COPY Pipfile* ./

RUN apk add --update --virtual .build-deps gcc g++ musl-dev && \
    pip install --no-cache-dir pipenv && \
    pipenv install --dev --system --deploy --clear

COPY app ./app

CMD ["pylint", "app/main.py", "app/ytdl.py"]